CREATE TABLE User(
	id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,	
	login VARCHAR(50) NOT NULL,
	password VARCHAR(255) NOT NULL, 
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	INDEX name (lastName, firstName)
);

CREATE TABLE Tournament(
	id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,	
	name VARCHAR(100) NOT NULL,
	description TEXT, 
	startDate DATE NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Team(
	id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,	
	name VARCHAR(100) NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Game(
	id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,	
	team1Id TINYINT UNSIGNED NOT NULL
		COMMENT "CONSTRAINT FOREIGN KEY (team1Id) REFERENCES Team(id)",
	team2Id TINYINT UNSIGNED NOT NULL
		COMMENT "CONSTRAINT FOREIGN KEY (team2Id) REFERENCES Team(id)",
	tournamentId TINYINT UNSIGNED NOT NULL
		COMMENT "CONSTRAINT FOREIGN KEY (tournamentId) REFERENCES Tournament(id)",
	startDate DATE NOT NULL,
	goals1 TINYINT UNSIGNED NOT NULL,
	goals2 TINYINT UNSIGNED NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,	
	INDEX (team1Id),
	INDEX (team2Id),
	INDEX (tournamentId)	
);

CREATE TABLE Draw(
	id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	description TEXT,
	tournamentId TINYINT UNSIGNED NOT NULL
		COMMENT "CONSTRAINT FOREIGN KEY (tournamentId) REFERENCES Tournament(id)",
	repeats TINYINT UNSIGNED NOT NULL,
	lot TINYINT(1) UNSIGNED NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP	
);

CREATE TABLE Bet(
	id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userId TINYINT UNSIGNED NOT NULL
		COMMENT "CONSTRAINT FOREIGN KEY (userId) REFERENCES User(id)",
	drawId TINYINT UNSIGNED NOT NULL
		COMMENT "CONSTRAINT FOREIGN KEY (drawId) REFERENCES Draw(id)",
	gameId TINYINT UNSIGNED NOT NULL
		COMMENT "CONSTRAINT FOREIGN KEY (gameId) REFERENCES Game(id)", 
		goals1 TINYINT UNSIGNED NOT NULL,
	goals2 TINYINT UNSIGNED NOT NULL,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	INDEX (userId),
	INDEX (drawId)
);

CREATE TABLE Participant(
	id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userId TINYINT UNSIGNED NOT NULL
		COMMENT "CONSTRAINT FOREIGN KEY (userId) REFERENCES User(id)",
	drawId TINYINT UNSIGNED NOT NULL
		COMMENT "CONSTRAINT FOREIGN KEY (drawId) REFERENCES Draw(id)",
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
